### ISSUE TITLE
Most likely, I found a bug

### ISSUE THREAD

**Issue by AntonProfiT** [critesjosh/azteccli#11]
Hi! I need help

I can't withdraw my money from Aztec! 
My Wallet L1 0xF278AC8e97dd418A3ce13307Fa1b44Ff87a18F7c
My wallet L2 0x0c1669810741bbffd63d0b7e25d6c2a8b8d58ff3d89d683c8227e0984ec90b9619b53d464dd44c86bb4bf443e1c95085cc74d46e5a1fae45546b2622ff8edbea

I have not been able to withdraw my ETH from the Aztec network for more than a month. I repeat the withdrawal attempt at least 50 times every day! I'm very tired!

I tried to solve the problem using 30 different computers and devices, as well as about 15 different ways of accessing the Internet. Nothing helps me!

The whole problem is definitely on the side of Aztec!

I may have found a bug in the Aztec network. There are more than 1000 incoming transactions on my wallet. Perhaps the Aztec network is not capable of servicing such wallets.

I ask the Aztec team to help solve my problem, since I have not been able to collect my ETH for more than a month.

<img width="1936" alt="1 — копия" src="https://user-images.githubusercontent.com/93988440/213102105-20d13028-be5d-4927-b7a4-91209a6c6ed1.png">
<img width="1971" alt="2 — копия" src="https://user-images.githubusercontent.com/93988440/213102123-b6cf167a-4a6c-4f60-979b-f8f4a3a8f848.png">

**Comment by AntonProfiT** [comment]
![Uploading 1.png…]()

**Comment by AntonProfiT** [comment]
<img width="530" alt="1" src="https://user-images.githubusercontent.com/93988440/213103177-54e81186-5382-4aab-95be-f15215f02492.png">

**Comment by AntonProfiT** [comment]
When I try to withdraw L2-L1 via zk.money, the site just freezes. It feels like when creating a transaction, the site is trying to scan all the blocks in which I have ever received transactions.

**Comment by critesjosh** [comment]
Looks like a bug with zkpay. 

Aztec applications need to download the entire state of the network in order to get your encrypted transactions, so it is trying to scan all the blocks. This can take some time if you have a slow internet connection. Did you try opening dev tools on zkmoney and enabling verbose message logging to see the status?

I am closing this as it is not an issue with azteccli

**Comment by AntonProfiT** [comment]
There are more than 1200 incoming transactions on my wallet! I have 1GBit of internet and a very powerful PC, but all this does not work for your network, which is built in such a way that I simply cannot get my money. 
What other ways can I get them?
<img width="1452" alt="1" src="https://user-images.githubusercontent.com/93988440/213251047-c166086f-4976-410d-b755-f45075d77958.png">

**Comment by AntonProfiT** [comment]
<img width="1419" alt="1" src="https://user-images.githubusercontent.com/93988440/213252476-89256e28-1033-45f6-83f0-6fe110436df1.png">
If I wait for about half an hour and indicate the withdrawal of 0.01ETH, then it works after half an hour, but the withdrawal fee is about 20%!
If I put more than 0.03ETH on the withdrawal, then I am not allowed to carry out this transaction even in 24 hours!
Therefore, I have the main question for you - how do I get my money in full?

**Comment by AntonProfiT** [comment]
When trying to withdraw 0.05ETH after a very long time, it showed me that I had to pay a 162% commission! Do you think it works fine?
<img width="936" alt="1" src="https://user-images.githubusercontent.com/93988440/213254988-4edbe1cd-c37c-4b0f-ad59-e1e7b65f0eb2.png">

**Comment by critesjosh** [comment]
This isn't a commission, its the real fee for posting the transaction to Aztec and then to Ethereum, so this will fluctuate with Ethereum gas prices, which have been pretty high lately

**Comment by critesjosh** [comment]
> 

This is way more than I've seen before. Are all of these personal transactions? Or are you using aztec as part of another service?

**Comment by AntonProfiT** [comment]
> 

I am a video blogger and author of a popular YouTube channel. I told everyone what Aztec is and how to use all its services, including zk.money and zk.pay
 I also made a text instruction that gained popularity for its quality - https://teletype.in/@anton_profit/aztec
In this instruction, I offered the guys to help test the Aztec network. We transferred ETH to the Aztec network, transferred funds to each other, engaged in stacking and the like. That's why there are so many incoming transactions on my wallet. People throw them to me in gratitude for my work and support on all issues.
But now I can't access my own funds...

**Comment by critesjosh** [comment]
Ok cool, just curious. Is the transaction fee always super high?

**Comment by AntonProfiT** [comment]
> Ok cool, just curious. Is the transaction fee always super high?

Yes, it is always very high, the minimum that I have seen is 15% of the withdrawal amount. I know what I'm talking about, since I haven't been able to get my funds for a month. I have been trying to withdraw funds every hour for a month. It just works terribly! I hope you will fix all this someday. 
Do I have the opportunity to withdraw funds from Aztec interacting directly with a smart contract?

**Comment by joeandrews** [comment]
This is likely due to chain transactions. Can you try and send a much smaller amount? e.g 0.00085zkETH

Each transaction can only spend 2 UTXO's if you have 1000 UTXO's the SDK will be trying to join these all together, resulting in the very high fee.

**Comment by AntonProfiT** [comment]
49% Fee
![Uploading 1.png…]()

**Comment by AntonProfiT** [comment]
49% Fee

<img width="936" alt="1" src="https://user-images.githubusercontent.com/93988440/213486791-1294335c-56e6-4d99-9eb3-cd93e6704533.png">

**Comment by AntonProfiT** [comment]
And 76% Fee when withdraw 0.5ETH
<img width="929" alt="1" src="https://user-images.githubusercontent.com/93988440/213488387-fc4753d7-faf9-4002-8fc1-5fd9b705749d.png">

**Comment by critesjosh** [comment]
Based on Joe's comment, this isn't a bug, but a result of the fact that you have tons of tiny notes that need to be added together (each of which requires a tx) in order to withdraw the requested amount.

**Comment by AntonProfiT** [comment]
Is this really how it should work? Why am I not experiencing similar difficulties in the main ETH network or any other blockchain? Are you going to solve the issue in this direction and make sure that the number of transactions does not affect the commission in any way? Or do you think that this is normal and should be so?

**Comment by critesjosh** [comment]
It's a consequence of the Aztec network architecture. Aztec uses a UTXO architecture, whereas EVM chains use an account model. UTXO models are better for networks with encrypted transactions , which other chains don't have.

**Comment by AntonProfiT** [comment]
I am an ordinary user and my opinion about this is that it is impossible to use it due to such large commissions. If you don't figure out how to solve the issue with commissions, I'm not sure that this can be a success
