### ISSUE TITLE
withdraw --time flag gives error

### ISSUE THREAD

**Issue by AdrianScott** [critesjosh/azteccli#2]
azteccli withdraw 0.3 --time instant
Failed to close the connection: TypeError: Cannot read properties of undefined (reading 'destroy')
 ›   Error: Unexpected arguments: --time, instant
 ›   See more help with --help

**Comment by critesjosh** [comment]
You are missing the `--recipient` flag. the recipient flag is [required](https://github.com/critesjosh/azteccli/blob/e871a96f45779a7e69625ff4f1e3b020404e897b/src/commands/withdraw.ts#L18) so if its not included it errors. Its unfortunate that the error message is so unhelpful, ill see if there is a way to improve that.

**Comment by critesjosh** [comment]
the recipient flag takes an address, so it would look something like  `azteccli withdraw 0.1 -r 0x2e782B05290A7fFfA137a81a2bad2446AD0DdFEB --time instant`
